=== djordjenrt5117/Vezba3/autooglas.dtd
<!DOCTYPE AutoOglas
[
<!ELEMENT Automobil (proizvodjac,model,godiste,farba,zapremina,transmisija,gorivo,cena,kontakt)>
<!ELEMENT proizvodjac (#PCDATA)>
<!ELEMENT model (#PCDATA)*>
<!ELEMENT godiste (#PCDATA)>
<!ELEMENT farba (("akril")|("metalik")+>
<!ELEMENT zapremina (("ccm")|("l"))>
<!ELEMENT transmisija (("manuelni")|("auto")+)>
<!ELEMENT gorivo (("da")|("ne")*)>
<!ELEMENT cena (("din")|("eur")+)>
<!ELEMENT kontakt (#PCDATA)>
]>

=== djordjenrt5117/Vezba3/autooglas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AutoOglas SYSTEM "autooglas.dtd">
<Automobil>
	<proizvodjac>Toyota</proizvodjac>
	<model tip="karavan">Korola</model>
	<godiste>2003</godiste>
	<farba tip="metalik">Plava</farba>
	<zapremina tip="l">1.4</zapremina>
	<transmisija tip="manuelni">5 brzina</transmisija>
	<gorivo tng="da">benzin</gorivo>
	<cena value="eur">2000</cena>
	<kontakt>123456789</kontakt>
</Automobil>
